version: 2

references:
  container_config: &container_config
    machine:
      services:
        - docker
  base_environment: &base_environment
      TERM: dumb
      IMAGE_VERSION: 1.13.2

  steps: &steps
    steps:
      - checkout
      - run:
          name: set docker daemon to experimental
          command: |-
            sudo sh -c 'echo '\''DOCKER_OPTS="--experimental=true"'\'' >> /etc/default/docker'
            sudo service docker restart
      - run:
          name: Build Docker image
          command: |-
            docker build ${DOCKER_FILE_PATH} --build-arg IMAGE_VERSION=${IMAGE_VERSION} --build-arg NDK_VERSION=${NDK_VERSION} --build-arg BAZEL_VERSION=${BAZEL_VERSION} --compress --squash -t menny/${IMAGE_NAME}:${IMAGE_VERSION}
      - run:
          name: Push image to Docker
          command: |-
            docker login -u ${DOCKER_USER} -p ${DOCKER_PASS}
            docker push menny/${IMAGE_NAME}:${IMAGE_VERSION}
            docker image tag menny/${IMAGE_NAME}:${IMAGE_VERSION} menny/${IMAGE_NAME}:latest
            docker push menny/${IMAGE_NAME}:latest

jobs:
  build_generic:
    <<: *container_config
    environment:
      <<: *base_environment
      IMAGE_NAME: android
      DOCKER_FILE_PATH: .
    <<: *steps
          
  build_latest_ndk:
    <<: *container_config
    environment:
      <<: *base_environment
      IMAGE_NAME: android_ndk
      NDK_VERSION: r20
      DOCKER_FILE_PATH: android_ndk/.
    <<: *steps

  build_ask_ndk:
    <<: *container_config
    environment:
      <<: *base_environment
      IMAGE_NAME: ndk_ask
      NDK_VERSION: r14b
      DOCKER_FILE_PATH: android_ndk/.
    <<: *steps

  build_android_bazel:
    <<: *container_config
    environment:
      <<: *base_environment
      IMAGE_NAME: android_bazel
      DOCKER_FILE_PATH: android_bazel/.
      BAZEL_VERSION: 1.1.0
    <<: *steps

  tag_at_repo:
    <<: *container_config
    environment:
      <<: *base_environment
    steps:
      - checkout
      - run:
          name: Tagging successful build
          command: |-
            git config --global user.email "circleci@evendanan.net"
            git config --global user.name "Circle CI"
            git tag -a ${IMAGE_VERSION} -m "Deployed"
            git push --tags origin

workflows:
  version: 2
  build_all_images:
    jobs:
      - build_generic:
          filters:
            branches:
              only: master
      - build_latest_ndk:
          requires:
            - build_generic
          filters:
            branches:
              only: master
      - build_ask_ndk:
          requires:
            - build_generic
          filters:
            branches:
              only: master
      - build_android_bazel:
          requires:
            - build_generic
          filters:
            branches:
              only: master
      - tag_at_repo:
          requires:
            - build_generic
            - build_ask_ndk
            - build_android_bazel
            - build_latest_ndk
          filters:
            branches:
              only: master
